### ISSUE TITLE
关于server.py及logic.py文件

### ISSUE THREAD

**Issue by HuangFuSL** [HuangFuSL/Werewolf#11]
有三个文件中出现了完全相同的代码

* `server.py`
* `server/server.py`
* `server/logic.py`

建议只保留其中的一份，删除其他所有重复的代码

另外，在Jupyter Notebook导出py文件后请手动删除如下形式的注释，或者使用IDE写代码

```python
# In [ ]
```

**Comment by HuangFuSL** [comment]
该问题已在`1219916`提交中解决

**Comment by hearts-six** [comment]
保留main中的server.py，以及server/logic.py，删除server/logic.py，现已使用pycharm进行编程
